export const employeeFieldMapping = {
//   userId: "Користувач",
  firstName: "Ім'я",
  lastName: "Прізвище",
  middleName: "По батькові",
  dateOfBirth: "Дата народження",
  personalMobile: "Особистий номер",
  corporateMobile: "Корпоративний номер",
  internalPhone: "Внутрішній номер",
  email: "Електронна пошта",
  corporateEmail: "Корпоративна пошта",
  gender: "Стать",
  departmentId: "Відділ",
  positionId: "Посада",
  role: "Роль",
  workplaceTypeId: "Тип місця роботи",
  photo: "Фото",
  residentialAddress: "Адреса проживання",
  quote: "Цитата",
};
