export const fieldNameMapping = {
    employeeDTO: "Створити працівника",
//   id: "Ідентифікатор",
  userId: "Користувач",
  firstName: "Ім'я",
  lastName: "Прізвище",
  middleName: "По батькові",
  dateOfBirth: "Дата народження",
  personalMobile: "Особистий номер",
  corporateMobile: "Корпоративний номер",
  internalPhone: "Внутрішній номер",
  personalEmail: "Особиста електронна пошта",
  workEmail: "Робоча електронна пошта",
  gender: "Стать",
  departmentId: "Відділ",
  managerId: "Керівник",
  positionId: "Посада",
  workplaceTypeId: "Тип місця роботи",
  employmentStartDate: "Дата початку роботи",
  country: "Країна",
  city: "Місто",
  street: "Вулиця",
  buildingNumber: "Номер будинку",
  apartmentNumber: "Номер квартири",
  quote: "Цитата",
  inspiration: "Хоббі",
  photo: "Фото",
};
